force-app/main/default/objects/RestoredMessage__c/RestoredMessage__c.object-meta.xml
<CustomObject>
    <label>Restored Message</label>
    <nameField>
        <label>Restored Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restored Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RestoredMessage__c/fields/FromAddress__c.field-meta.xml
<CustomField>
    <fullName>FromAddress__c</fullName>
    <label>From Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RestoredMessage__c/fields/TextBody__c.field-meta.xml
<CustomField>
    <fullName>TextBody__c</fullName>
    <label>Text Body</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/tests/controllers/ArchivedMessagesController_Test.cls
@IsTest
private class ArchivedMessagesController_Test {

    @IsTest
    static void getMessages_isSuccessful() {

        HttpCalloutUtilityMock mock = new HttpCalloutUtilityMock(TestFactory.statusCode, TestFactory.status, TestFactory.createTestResponse(), TestFactory.createResponseHeaders());
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        List<ResponseDTO> response = ArchivedMessagesController.getMessages('500xxxxx');
        Test.stopTest();

        System.assertNotEquals(null, response);
        System.assertNotEquals(null, response[0]);
        System.assertEquals(5, response.size());

    }

    static void restoreMessage_isSuccessful() {
        Test.startTest();
        Boolean result = ArchivedMessagesController.restoreMessage(TestFactory.externalId, TestFactory.fromAddress, TestFactory.subject, TestFactory.textBody);

        RestoredMessage__c createdMessage = [SELECT externalId__c, fromAddress__c, subject__c, textBody__c FROM RestoredMessage__c LIMIT 1];
        Test.stopTest();

        System.assert(result, true);
        System.assertEquals(TestFactory.externalId, createdMessage.externalId__c);
        System.assertEquals(TestFactory.subject, createdMessage.subject__c);
    }
}